#!/bin/sh

#SBATCH --job-name=ds000002-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000002-mriqc/.reproman/jobs/local/20211203-170033-2249/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000002-mriqc/.reproman/jobs/local/20211203-170033-2249/stderr

#SBATCH --nodes=4
#SBATCH --ntasks=17
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000002-mriqc/.reproman/jobs/local/20211203-170033-2249

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 16); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

export REMORA_TMPDIR="$STAGING"
remora "$LAUNCHER_DIR"/paramrun